Incorrect parent
UofS-Pulse-Binfo/germ_summary pull request #14
Opened 2019-09-19 17:53 UTC by reynoldtan

This PR proposes major changes to the code-base of this module. The main change being the query considering the implementation of a 'caretaker/sitter' in references to a stock. In addition, this pr eliminated redundant query (ie. sample shown in tool tip text) and created system variables for frequently used ontologies (ie. is_selection_of).

## Metadata

 - Issue https://github.com/UofS-Pulse-Binfo/germ_summary/issues/13 Incorrect summary count per parent cross.

- [X] I feel this PR is ready to be merged.
- [ ] This PR is dependent upon [PR #/ nothing]

Documentation:
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

## Description

## Dependencies

## Testing?
1. Disable and uninstall this module.
2. Update files.
3. Enable module.

I have verified summary count of crosses where it is less than a hundred. Unknown by Unknown and culinaris and culinaris both returned count more than 700+, I've looked at some items but I could not confirm nor verify its correctness. 

- [ ] I tested on a generic Tripal Site
- [X] I tested on a KnowPulse Clone
- [ ] This PR includes automated testing

2019-09-19 20:28 UTC, laceysanderson commented
For more context when reviewing:
The broken version of the matrix looked like this:
<img width="1151" alt="Screen Shot 2019-09-19 at 2 24 15 PM" src="https://user-images.githubusercontent.com/1566301/65278407-4a485400-dae9-11e9-9685-d736f30fdd37.png">
Notice the large number of `unknown x unknown`

The module has been updated on dev/fresh. Now we need to check that 
1. the counts are correct for each cell by cross referencing the RIL search
2. when a count is clicked on you see the crosses you expect based on known parentage.
3. generation information is filled in if available.
4. RIL name link goes to the germplasm page (i.e. LR-18)

2019-09-20 19:48 UTC, reynoldtan commented
Confirmed! 
1. I've check the summary count matched the result in RIL search
2. Stocks the count was based on matched the count in the cell, as well as the stocks in the RIL search per cross.
3. Tested F2, F3, F4, F5, F6, F7, F8 and Rill Complete.
Could not find F1 field though.

2019-09-23 16:16 UTC, ruobinLiu commented
Checked, no issues was found.

2019-09-24 15:49 UTC, laceysanderson requested changes
Links don't work for to go from matrix to listing for non-Lens matrix. For example, when I go to `germplasm/summary/Phaseolus` and click on `9` for `vulgaris x vulgaris` I am redirected to the Lens matrix...

Other then that, everything looks good :-)

2019-09-24 15:49 UTC, laceysanderson commented on germ_summary.module
> +          drupal_set_message('Stocks not found.', 'warning');
```suggestion
          drupal_set_message('There are no RILs for this combination of species.', 'warning');
```

2019-09-29 15:59 UTC, laceysanderson approved these changes

2019-09-29 15:59 UTC, merged